import type { Well } from '../../entities/well/model/types'
import type { InterpretationInterval, InterpretationWorkspace } from '../../entities/well-interpretation/model/types'
import { demoDatabase, type DemoRecord } from './demoDatabase'
const now = () => new Date().toISOString()
const rec = <T>(id: string, entityType: string, well: Well, data: T, status = 'active'): DemoRecord<T> => ({ id, entityType, objectId: well.id, scopeId: well.site, status, updatedAt: now(), data: structuredClone(data) })
const interval = (id: string, kind: InterpretationInterval['kind'], from: number, to: number, title: string, source: InterpretationInterval['source'], state: InterpretationInterval['state'], method: string, properties?: InterpretationInterval['properties']): InterpretationInterval => ({ id, kind, from, to, title, source, state, method, version: 1, evidence: ['Synthetic GR/RES curve chunk', 'E05 LogRun version 1'], properties })
function seed(well: Well): InterpretationWorkspace { const permeable = [interval(`PERM-${well.id}-01`, 'permeable', 374, 418, 'Проницаемый интервал', 'manual', 'draft', 'Manual KS', { ks: 5.8 })]; const filtration = [interval(`FILT-${well.id}-01`, 'filtration', 380, 414, 'Фильтрационный слой', 'manual', 'accepted', 'Synthetic filtration', { filtration: 0.31 })]; const ore = [interval(`ORE-${well.id}-01`, 'ore', 388, 422, 'Рудный интервал', 'manual', 'preliminary', 'Direct assay composite', { grade: 0.42 })]; return { wellId: well.id, permeable, filtration, differential: [interval(`DIFF-NC-${well.id}-01`, 'differential', 350, 366, 'No-correction control', 'adapter', 'no-correction', 'Synthetic exclusion rule')], ore, tech: [], manual: [interval(`MAN-${well.id}-01`, 'manual', 388, 422, 'Ручная интерпретация', 'manual', 'draft', 'Expert boundary', { grade: .42 })], workflow: 'draft', version: 1, updatedAt: '2026-08-24T00:00:00.000Z' } }
export class DemoWellInterpretationRepository {
  async get(well: Well) { const existing = await demoDatabase.get<DemoRecord<InterpretationWorkspace>>('records', `well-interpretation:${well.id}`); if (existing) return structuredClone(existing.data); const value = seed(well); await this.persist(well, value, 'interpretation.seeded'); return value }
  async save(well: Well, current: InterpretationWorkspace, next: InterpretationWorkspace, eventType: string) { const latest = await this.get(well); if (latest.version !== current.version) throw new Error('VERSION_CONFLICT: интерпретация изменилась в другой вкладке.'); const value = { ...structuredClone(next), version: latest.version + 1, updatedAt: now() }; await this.persist(well, value, eventType); return value }
  private async persist(well: Well, value: InterpretationWorkspace, eventType: string) { await demoDatabase.transaction(['records','versions','relations','auditEvents','jobs','artifacts'], async (tx) => { const jobId=`JOB-INT-${well.id}-V${value.version}`; await tx.put('records',rec(`well-interpretation:${well.id}`,'well-interpretation-workspace',well,value,value.workflow)); for(const item of [...value.permeable,...value.filtration,...value.differential,...value.ore,...value.tech,...value.manual,...(value.autoProposal??[]),...(value.aiProposal?.intervals??[]),...(value.resolved??[])]) await tx.put('records',rec(`interpretation:${item.id}`,'interpretation-interval',well,item,item.state)); if(value.aiProposal) await tx.put('records',rec(`ai-proposal:${value.aiProposal.id}`,'ai-interpretation',well,value.aiProposal,value.aiProposal.status)); await tx.put('versions',{id:`INTERPRETATION-${well.id}-V${value.version}`,objectId:`well-interpretation:${well.id}`,version:value.version,status:value.workflow,createdAt:value.updatedAt,data:value}); for(const item of value.resolved??[]) for(const source of [...value.manual,...(value.aiProposal?.intervals??[])]) await tx.put('relations',{id:`REL-RES-${item.id}-${source.id}`,fromId:`interpretation:${item.id}`,toId:`interpretation:${source.id}`,type:'resolved-from',updatedAt:value.updatedAt}); await tx.put('jobs',{id:jobId,kind:eventType.includes('ai')?'ai-interpretation':eventType.includes('auto')?'automatic-ks':'interpretation-resolution',status:'succeeded',createdAt:value.updatedAt,completedAt:value.updatedAt,synthetic:true}); await tx.put('artifacts',{id:`ART-INT-${well.id}-V${value.version}`,kind:eventType.includes('ai')?'ai-evidence':'interpretation-diff',name:`${well.code}-interpretation-v${value.version}`,createdAt:value.updatedAt,synthetic:true}); await tx.put('auditEvents',{id:`AUD-${eventType}-${well.id}-V${value.version}`,eventType,entityType:'well-interpretation',entityId:well.id,actor:{id:'PERSON-R2-GEOPHYSICIST',type:'user',name:'Марат Омаров · synthetic'},occurredAt:value.updatedAt,status:'accepted',payload:{metadata:{synthetic:true,jobId}}}) }) }
}
export const demoWellInterpretationRepository = new DemoWellInterpretationRepository()