import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Bot, CheckCircle2, GitCompareArrows, Layers3, Play, Save, Send, Sparkles } from 'lucide-react'
import { useState } from 'react'
import type { Well } from '../../../entities/well/model/types'
import type { InterpretationInterval, InterpretationWorkspace } from '../../../entities/well-interpretation/model/types'
import { fetchWellInterpretationWorkspace, saveWellInterpretationWorkspace } from '../../../repository/api'
import { Button } from '../../../shared/ui/Button'
import { Panel } from '../../../shared/ui/Panel'

const make = (id: string, kind: InterpretationInterval['kind'], from: number, to: number, title: string, source: InterpretationInterval['source'], state: InterpretationInterval['state'], method: string): InterpretationInterval => ({ id, kind, from, to, title, source, state, method, version: 1, evidence: ['Synthetic E05 curve source', 'Deterministic demo rule'] })
const rows = (items: InterpretationInterval[]) => <div className="samples-table"><div className="samples-table__head"><span>Интервал</span><span>Источник</span><span>Метод</span><span>State</span></div>{items.map((item) => <div key={item.id}><span>{item.from}–{item.to} м · {item.title}</span><span>{item.source}</span><span>{item.method}</span><span>{item.state}</span></div>)}</div>
const compactRows = (items: InterpretationInterval[]) => <div className="interpretation-compact-list">{items.map((item) => <article key={item.id}><div className="interpretation-compact-list__interval"><span>Интервал</span><strong>{item.from}–{item.to} м</strong><small>{item.title}</small></div><div><span>Источник</span><strong>{item.source}</strong></div><div><span>Метод</span><strong>{item.method}</strong></div><div><span>Статус</span><strong>{item.state}</strong></div></article>)}</div>

export function InterpretationDataWorkspace({ well }: { well: Well }) {
  const client = useQueryClient()
  const query = useQuery({ queryKey: ['well-interpretation', well.id], queryFn: () => fetchWellInterpretationWorkspace(well.id) })
  const [draft, setDraft] = useState<InterpretationWorkspace | null>(null)
  const workspace = draft ?? query.data
  const save = useMutation({ mutationFn: () => saveWellInterpretationWorkspace(well.id, query.data!, draft!, draft!.workflow === 'published' ? 'interpretation.published' : draft!.resolved ? 'interpretation.resolved' : draft!.aiProposal ? 'interpretation.ai.created' : draft!.autoProposal ? 'interpretation.auto.ks.created' : 'interpretation.manual.saved'), onSuccess: (next) => { setDraft(null); client.setQueryData(['well-interpretation', well.id], next) } })
  if (query.isLoading || !workspace) return <div className="page-loading page-loading--inline"><span /><p>Загружаем интерпретационный workspace…</p></div>
  if (query.isError) return <div className="form-alert form-alert--error">{String(query.error.message)}</div>
  const change = (next: InterpretationWorkspace) => setDraft(next)
  const addManual = () => change({ ...workspace, manual: [...workspace.manual, { ...make(`MAN-${workspace.version}`, 'manual', 424, 446, 'Ручная граница', 'manual', 'draft', 'Expert reason'), reason: 'Synthetic expert basis: GR/RES boundary', properties: { grade: .36 } }] })
  const runAuto = () => change({ ...workspace, autoProposal: [make(`AUTO-KS-${workspace.version}`, 'permeable', 378, 416, 'KS auto proposal', 'automatic', 'proposed', 'Synthetic KS · min thickness 2 м')] })
  const importDifferential = () => change({ ...workspace, differential: [...workspace.differential, make(`DIFF-${workspace.version}`, 'differential', 390, 410, 'Differential interval', 'adapter', 'draft', 'Fake adapter preview')] })
  const editOre = () => change({ ...workspace, ore: [...workspace.ore, make(`ORE-COMP-${workspace.version}`, 'ore', 392, 416, 'Composite ore after trim/split', 'manual', 'preliminary', 'Direct/differential connect')], tech: [...workspace.tech, make(`TECH-${workspace.version}`, 'tech', 392, 416, 'Tech alignment proposal', 'automatic', 'proposed', 'Alignment from permeable interval')] })
  const runAi = () => change({ ...workspace, aiProposal: { id: `AI-${workspace.version}`, modelVersion: 'synthetic-geology-v0.4', confidence: .82, calibration: 'Synthetic calibration set A', status: 'proposed', evidence: ['GR spike acknowledged', 'RES crossover 388–422 м'], intervals: [make(`AI-INT-${workspace.version}`, 'ai', 384, 420, 'AI ore boundary', 'AI synthetic', 'proposed', 'Deterministic synthetic classifier')] } })
  const resolve = () => { const manual = workspace.manual[0]!; const ai = workspace.aiProposal?.intervals[0]; if (!ai) return; change({ ...workspace, resolved: [{ ...make(`RES-${workspace.version}`, 'resolved', Math.min(manual.from, ai.from), Math.max(manual.to, ai.to), 'Human resolved composite', 'manual', 'accepted', 'Manual + AI decision'), reason: 'Эксперт выбрал скорректированную границу после сравнения' }], aiProposal: { ...workspace.aiProposal!, status: 'resolved' } }) }
  const transition = () => change({ ...workspace, workflow: workspace.workflow === 'draft' ? 'in_review' : workspace.workflow === 'in_review' ? 'approved' : 'published' })
  return <div className="object-workspace">
    {save.error && <div className="form-alert form-alert--error">{String(save.error)}</div>}
    <Panel title="Интерпретация проницаемости и фильтрации" description="GEOX-E06 · manual/automatic proposals сохраняются отдельно"><div className="object-content-grid"><div className="object-content-grid__main">{rows(workspace.permeable)}<div className="workflow-actions"><Button size="sm" variant="secondary" onClick={() => change({ ...workspace, permeable: [...workspace.permeable, make(`PERM-${workspace.version}`, 'permeable', 430, 452, 'Manual permeable interval', 'manual', 'draft', 'Manual KS')] })}>Manual interval</Button><Button size="sm" variant="secondary" onClick={runAuto}><Play size={14} /> Run auto KS</Button></div>{workspace.autoProposal && <div className="validation-list"><div className="validation-item validation-item--info"><span><strong>Auto KS proposal · min thickness 2 м</strong><small>{workspace.autoProposal[0]!.from}–{workspace.autoProposal[0]!.to} м · apply only after save</small></span></div></div>}</div><aside>{compactRows(workspace.filtration)}<p className="save-hint">Фильтрационные свойства и метод synthetic; не расчёт для производства.</p></aside></div></Panel>
    <div className="object-content-grid"><div className="object-content-grid__main"><Panel title="Differential, ore and tech alignment" description="Preview не меняет утверждённый source"><div className="workflow-actions"><Button size="sm" variant="secondary" onClick={importDifferential}>Fake differential adapter</Button><Button size="sm" variant="secondary" onClick={editOre}><Layers3 size={14} /> Connect / trim / split ore</Button></div>{rows([...workspace.differential, ...workspace.ore, ...workspace.tech])}<p className="save-hint">`preliminary` и `no-correction` статусы видимы и исключены из demo reserve selector.</p></Panel></div><aside><Panel title="Manual interpretation" description="Несколько интервалов, evidence и причина обязательны">{compactRows(workspace.manual)}<Button size="sm" variant="secondary" onClick={addManual}>Добавить expert interval</Button></Panel></aside></div>
    <Panel title="AI proposal → human resolution" description="AI не перезаписывает manual и не публикуется без решения специалиста"><div className="object-content-grid"><div className="object-content-grid__main">{workspace.aiProposal ? <div className="validation-list"><div className="validation-item validation-item--info"><Bot size={16} /><span><strong>{workspace.aiProposal.modelVersion} · confidence {workspace.aiProposal.confidence}</strong><small>{workspace.aiProposal.calibration} · {workspace.aiProposal.evidence.join(' · ')}</small></span></div>{rows(workspace.aiProposal.intervals)}</div> : <p className="empty-state">AI proposal ещё не запущен.</p>}<div className="workflow-actions"><Button size="sm" variant="secondary" onClick={runAi}><Sparkles size={14} /> Run synthetic AI</Button><Button size="sm" disabled={!workspace.aiProposal} onClick={resolve}><GitCompareArrows size={14} /> Human resolution</Button></div></div><aside>{workspace.resolved ? <div className="validation-list"><div className="validation-item validation-item--success"><CheckCircle2 size={16} /><span><strong>Resolved composite</strong><small>{workspace.resolved[0]!.from}–{workspace.resolved[0]!.to} м · {workspace.resolved[0]!.reason}</small></span></div></div> : <p className="save-hint">Сначала compare manual и AI, затем создайте human resolved version.</p>}</aside></div></Panel>
    <div className="workspace-savebar"><div><strong>Workflow: {workspace.workflow} · workspace v{workspace.version}</strong><span>Review → approve → publish создают новую version/audit; approved input не меняется на месте.</span></div><div className="workflow-actions"><Button size="sm" variant="secondary" disabled={!draft || workspace.workflow === 'published'} onClick={transition}><Send size={14} /> {workspace.workflow === 'draft' ? 'Submit review' : workspace.workflow === 'in_review' ? 'Approve' : 'Publish'}</Button><Button disabled={!draft || save.isPending} onClick={() => save.mutate()}><Save size={16} /> {save.isPending ? 'Сохраняем…' : 'Сохранить E06'}</Button></div></div>
  </div>
}