import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Crosshair, FileCheck2, FileUp, RadioTower, Rows3, Save, ScanLine } from 'lucide-react'
import { useState } from 'react'
import type { LogRunStatus, Well } from '../../../entities/well/model/types'
import { validateDepthIntervals } from '../../../entities/well/lib/validateDepthIntervals'
import { fetchWellLogs } from '../../../repository/api'
import { Badge } from '../../../shared/ui/Badge'
import { Button } from '../../../shared/ui/Button'
import { Panel } from '../../../shared/ui/Panel'

const tone: Record<LogRunStatus, 'neutral' | 'warning' | 'info' | 'success'> = { 'Импортирован': 'neutral', 'Есть замечания QC': 'warning', 'QC пройден': 'info', 'Интерпретирован': 'success', 'Утверждён': 'success' }
export function LogsWorkspace({ well }: { well: Well }) {
  const { data, isLoading } = useQuery({ queryKey: ['well-logs', well.id], queryFn: () => fetchWellLogs(well.id) })
  const [selectedId, setSelectedId] = useState('LOG-1042-0418')
  const [importStep, setImportStep] = useState<number | undefined>()
  const [viewerId, setViewerId] = useState<string | undefined>()
  if (isLoading || !data) return <div className="page-loading page-loading--inline"><span /><p>Загружаем наборы ГИС…</p></div>
  const selected = data.find((item) => item.id === selectedId) ?? data[0]
  if (importStep !== undefined) return <LogImportWizard well={well} step={importStep} onStep={setImportStep} onClose={() => setImportStep(undefined)} />
  if (viewerId) { const log = data.find((item) => item.id === viewerId); if (log) return <LogViewer well={well} log={log} onClose={() => setViewerId(undefined)} /> }
  return <div className="object-workspace logs-workspace"><div className="logs-workspace__summary"><div><Badge tone="info">GEO-12</Badge><strong>Наборы геофизических исследований</strong><span>Источники, глубинная привязка, состав кривых и QC по {well.code}.</span></div><Button size="sm" onClick={() => setImportStep(0)}><FileUp size={15} /> Импорт LAS/DAT</Button></div><div className="logs-layout"><Panel title="Реестр исследований" description="Выберите набор для QC и просмотра"><div className="logs-list">{data.map((log) => <button type="button" key={log.id} className={log.id === selected?.id ? 'is-selected' : ''} onClick={() => setSelectedId(log.id)}><span className="logs-list__icon"><RadioTower size={18} /></span><span><strong>{log.name}</strong><small>{log.id} · {log.importedAt}</small><em>{log.from}–{log.to} м · шаг {log.step} м</em></span><Badge tone={tone[log.status]}>{log.status}</Badge></button>)}</div></Panel>{selected && <Panel title="QC и состав набора" description="GEO-12 · статусы источника и проверки"><div className="log-inspector"><div className="log-inspector__meta"><span><ScanLine size={17} /><strong>{selected.from}–{selected.to} м</strong><small>Глубина · {selected.depthUnit}</small></span><span><Rows3 size={17} /><strong>{selected.curves.join(' · ')}</strong><small>{selected.curves.length} кривые · {selected.source}</small></span></div><div className={selected.qcIssues ? 'log-qc log-qc--warning' : 'log-qc'}>{selected.qcIssues ? <AlertTriangle size={19} /> : <CheckCircle2 size={19} />}<div><strong>{selected.qcIssues ? `${selected.qcIssues} замечания QC требуют решения` : 'QC пройдем без замечаний'}</strong><span>{selected.qcIssues ? 'Пропуск 281,6–283,0 м и spike GR на 418,2 м. Viewer покажет их на треке.' : 'Набор готов к интерпретации и сравнению с другими источниками.'}</span></div></div><div className="log-inspector__actions"><Button size="sm" variant="secondary" onClick={() => setViewerId(selected.id)}>Открыть viewer</Button><Button size="sm" variant="secondary">Проверить QC</Button></div></div></Panel>}</div></div>
}

function LogViewer({ well, log, onClose }: { well: Well; log: Awaited<ReturnType<typeof fetchWellLogs>>[number]; onClose: () => void }) {
  const [depth, setDepth] = useState(418.2)
  const tracks = [['GR', 'Gamma Ray', '0–150 API'], ['SP', 'Self potential', '−80–40 mV'], ['RES', 'Resistivity', '0–120 Ωm']] as const
  return <div className="logviewer"><header className="logviewer__header"><div><p className="eyebrow">GEO-14 · LOGVIEWER</p><h1>{log.name}</h1><span>{well.code} · {log.id} · {log.from}–{log.to} м · {log.step} м</span></div><Button variant="secondary" onClick={onClose}><ChevronLeft size={16} /> К реестру</Button></header><div className="logviewer__toolbar"><span><Crosshair size={16} /> Курсор: {depth.toFixed(1)} м</span><input aria-label="Глубина курсора" type="range" min={log.from} max={log.to} step=".2" value={depth} onChange={(event) => setDepth(Number(event.target.value))} /><Badge tone={log.qcIssues ? 'warning' : 'success'}>{log.qcIssues ? `${log.qcIssues} QC issue` : 'QC passed'}</Badge></div><section className="logviewer__canvas"><div className="logviewer__ruler">{[0,.25,.5,.75,1].map((ratio) => <span key={ratio} style={{ top: `${ratio * 100}%` }}>{Math.round(log.from + (log.to-log.from)*ratio)} м</span>)}</div><div className="logviewer__track logviewer__track--lith"><strong>Литология</strong><i style={{top:'0%',height:'20%'}} /><i style={{top:'20%',height:'32%'}} /><i style={{top:'52%',height:'28%'}} /><i style={{top:'80%',height:'20%'}} /></div>{tracks.map(([code,label,unit], index) => <div className="logviewer__track logviewer__track--curve" key={code}><strong>{code}<small>{label} · {unit}</small></strong><svg viewBox="0 0 100 600" preserveAspectRatio="none"><path d={index === 0 ? 'M48 0 C20 60 78 120 43 180 S78 300 28 350 S80 465 45 600' : index === 1 ? 'M70 0 C42 60 78 130 35 200 S75 320 40 420 S69 510 30 600' : 'M28 0 C72 70 35 130 75 205 S22 310 68 400 S32 520 66 600'} /></svg></div>)}<div className="logviewer__cursor" style={{top:`${(depth-log.from)/(log.to-log.from)*100}%`}}><span>{depth.toFixed(1)} м</span></div>{log.qcIssues > 0 && <div className="logviewer__marker" style={{top:`${(281.6-log.from)/(log.to-log.from)*100}%`}}>Gap 1,4 м</div>}</section><aside className="logviewer__inspector"><Panel title="Inspector" description="Значения по курсору"><dl><div><dt>GR</dt><dd>{(62 + depth % 17).toFixed(1)} API</dd></div><div><dt>SP</dt><dd>{(-22 + depth % 9).toFixed(1)} mV</dd></div><div><dt>RES</dt><dd>{(24 + depth % 31).toFixed(1)} Ωm</dd></div><div><dt>Источник</dt><dd>{log.source} · {log.importedAt}</dd></div></dl></Panel></aside><ManualInterpretation depth={depth} maxDepth={log.to} /></div>
}

function ManualInterpretation({ depth, maxDepth }: { depth: number; maxDepth: number }) {
  const [interval, setInterval] = useState({ from: 388, to: 422, category: 'Рудный интервал', confidence: 0.82, reason: '' })
  const [saved, setSaved] = useState(false)
  const issues = validateDepthIntervals([{ id: 'MANUAL-01', from: interval.from, to: interval.to }], maxDepth)
  const valid = issues.length === 0 && interval.reason.trim().length >= 8
  return <Panel className="manual-interpretation" title="Ручная интерпретация" description={`GEO-15 · исходная глубина курсора ${depth.toFixed(1)} м`}><div className="manual-interpretation__grid"><label><span>От, м</span><input type="number" value={interval.from} onChange={(e) => { setInterval({ ...interval, from: Number(e.target.value) }); setSaved(false) }} /></label><label><span>До, м</span><input type="number" value={interval.to} onChange={(e) => { setInterval({ ...interval, to: Number(e.target.value) }); setSaved(false) }} /></label><label><span>Категория</span><select value={interval.category} onChange={(e) => { setInterval({ ...interval, category: e.target.value }); setSaved(false) }}><option>Рудный интервал</option><option>Вмещающие породы</option><option>Граница уточняется</option></select></label><label><span>Уверенность</span><input type="number" min="0" max="1" step=".01" value={interval.confidence} onChange={(e) => { setInterval({ ...interval, confidence: Number(e.target.value) }); setSaved(false) }} /></label><label className="manual-interpretation__wide"><span>Экспертное обоснование</span><textarea value={interval.reason} placeholder="Не менее 8 символов: укажите кривые и причину границы" onChange={(e) => { setInterval({ ...interval, reason: e.target.value }); setSaved(false) }} /></label></div>{issues.length > 0 && <div className="validation-list">{issues.map((issue) => <div className="validation-item validation-item--error" key={issue.code}><AlertTriangle size={15} />{issue.message}</div>)}</div>}<div className="manual-interpretation__footer"><span>{saved ? 'Ручная интерпретация сохранена в черновике.' : 'Для сохранения требуется корректный интервал и обоснование.'}</span><Button size="sm" disabled={!valid} onClick={() => setSaved(true)}><Save size={15} /> Сохранить черновик</Button></div></Panel>
}

function LogImportWizard({ well, step, onStep, onClose }: { well: Well; step: number; onStep: (step: number) => void; onClose: () => void }) {
  const complete = step === 3
  const titles = ['Файл', 'Каналы и глубина', 'QC preview', 'Результат']
  return <div className="wizard-page"><header className="wizard-header"><div><p className="eyebrow">GEO-13 · ИМПОРТ</p><h1>Импорт LAS/DAT</h1><p>Набор создаётся только после явного подтверждения QC-результата.</p></div><Button variant="quiet" onClick={onClose}>Закрыть</Button></header><ol className="wizard-steps">{titles.map((title, index) => <li key={title} className={index === step ? 'is-active' : index < step ? 'is-complete' : ''}><span>{index + 1}</span><strong>{title}</strong></li>)}</ol><Panel className="wizard-card"><section className="wizard-section"><div className="wizard-section__intro"><FileUp size={22} /><div>{step === 0 && <><h2>Файл и назначение</h2><p><strong>WELL-1042_QC_2026-08.LAS</strong> · 18,4 MB · распознан формат LAS 2.0. Набор будет связан со скважиной {well.code}.</p></>}{step === 1 && <><h2>Глубина и mapping каналов</h2><p>Depth channel: <strong>DEPT, м</strong>; шаг 0,2 м. Распознаны GR → Gamma Ray, SP → Self Potential, RES → Resistivity.</p></>}{step === 2 && <><h2>QC preview</h2><p>Найдено 2 замечания: gap 281,6–283,0 м и spike GR на 418,2 м. Импорт разрешён, но набор получит статус «Есть замечания QC».</p></>}{complete && <><h2>Набор создан</h2><p>Создан набор <strong>LOG-WELL-1042-DRAFT</strong>. Он доступен в реестре как «Есть замечания QC» и готов к просмотру.</p></>}</div></div></section><footer className="wizard-actions">{step > 0 && !complete && <Button variant="secondary" onClick={() => onStep(step - 1)}><ChevronLeft size={16} /> Назад</Button>}<span>{complete ? 'Импорт зафиксирован' : 'Изменения будут сохранены после подтверждения'}</span>{!complete && <Button onClick={() => onStep(step + 1)}>{step === 2 ? <><FileCheck2 size={16} /> Подтвердить импорт</> : <>Далее <ChevronRight size={16} /></>}</Button>}{complete && <Button onClick={onClose}>Вернуться в реестр</Button>}</footer></Panel></div>
}
