/**
 * Domain colour palette — the single source of truth for every colour that
 * carries geological meaning (curves, lithology, well symbols, plan chrome).
 *
 * Unlike the semantic theme tokens in `src/styles/theme.css`, these colours are
 * a *standard*, not a theme: they are identical in light and dark mode so that
 * a printed plan, a PNG export and the screen show the same geology.
 *
 * Consumed twice:
 *  - as CSS variables — `src/styles/domain.css`, generated by
 *    `pnpm --filter @kapgeo/ui tokens:build` (`scripts/build-tokens.mjs`);
 *  - as this typed object — for Canvas/SVG renderers that cannot read Tailwind
 *    classes (`@kapgeo/geo-viz` well log tablet, plan symbols).
 *
 * NOTE: all lithology fills and well symbol colours are PLACEHOLDERS chosen to
 * be readable and mutually distinguishable on a geology map. They must be
 * replaced with the official legend symbols of СТ НАК 16-2014 once the customer
 * provides the standard (colours, hatch patterns and symbol shapes).
 */

/** Well log curve colours, keyed by log type (see docs/architecture/overview.md). */
const curves = {
  /** ГК — gamma ray. */
  GR: '#2e7d32',
  /** КС — resistivity. */
  RS: '#c62828',
  /** ПС — spontaneous potential. */
  SP: '#1565c0',
  /** ИК — induction. */
  IL: '#6a1b9a',
  /** ТК — current log. */
  TK: '#ef6c00',
  /** КНД — neutron fission. */
  KND: '#00838f',
  /** Каверномер — caliper. */
  CAL: '#5d4037',
  /** Расходометрия — flow meter. */
  FLOW: '#ad1457',
} as const;

/** Lithology fills for well columns, sections and legends. PLACEHOLDER. */
const lithology = {
  sand: '#f2dc9b',
  clay: '#8d9db6',
  silt: '#cec39c',
  gravel: '#d9b07c',
  sandstone: '#e5c274',
  limestone: '#bcd6e8',
  marl: '#bed3b6',
  ore: '#8e24aa',
  unknown: '#d4d4d4',
} as const;

/** Well symbol colours by well kind (назначение скважины). PLACEHOLDER. */
const wellKind = {
  /** Откачная (добычная). */
  production: { fill: '#e53935', stroke: '#8e1c1a' },
  /** Закачная. */
  injection: { fill: '#1e88e5', stroke: '#0d47a1' },
  /** Наблюдательная. */
  observation: { fill: '#43a047', stroke: '#1b5e20' },
  /** Разведочная. */
  exploration: { fill: '#fb8c00', stroke: '#e65100' },
  other: { fill: '#9e9e9e', stroke: '#616161' },
} as const;

/** Well symbol colours by operational status (состояние скважины). PLACEHOLDER. */
const wellStatus = {
  /** В работе. */
  active: { fill: '#2e7d32', stroke: '#1b5e20' },
  /** В простое. */
  idle: { fill: '#fdd835', stroke: '#f9a825' },
  /** В ремонте. */
  repair: { fill: '#fb8c00', stroke: '#e65100' },
  /** На закислении. */
  acidification: { fill: '#8e24aa', stroke: '#4a148c' },
  /** Ликвидированная. */
  abandoned: { fill: '#757575', stroke: '#424242' },
} as const;

/** Plan (2D deposit map) chrome that must look the same in both themes. */
const plan = {
  grid: '#c9ced6',
  /** Axis lines and track frames of the plan / well log chrome. */
  axis: '#94a3b8',
  /** Tick and axis labels. */
  label: '#475569',
  selection: '#ffb300',
  hover: '#29b6f6',
  sectionLine: '#d81b60',
  blockContour: '#37474f',
} as const;

export const domainTokens = { curves, lithology, wellKind, wellStatus, plan } as const;

export type DomainTokens = typeof domainTokens;

export type CurveType = keyof DomainTokens['curves'];
export type LithologyType = keyof DomainTokens['lithology'];
export type WellKind = keyof DomainTokens['wellKind'];
export type WellStatus = keyof DomainTokens['wellStatus'];
export type PlanToken = keyof DomainTokens['plan'];

type LeafPath<T, Prefix extends string = ''> = {
  [K in keyof T & string]: T[K] extends string ? `${Prefix}${K}` : LeafPath<T[K], `${Prefix}${K}.`>;
}[keyof T & string];

/** Dot path of any leaf colour, e.g. `'curves.GR'`, `'wellKind.production.stroke'`. */
export type DomainTokenPath = LeafPath<DomainTokens>;

/** CSS variable prefix per token group. */
const groupPrefix = {
  curves: 'curve',
  lithology: 'litho',
  wellKind: 'well-kind',
  wellStatus: 'well-status',
  plan: 'plan',
} as const satisfies Record<keyof DomainTokens, string>;

function kebabCase(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function varName(group: keyof DomainTokens, path: readonly string[]): string {
  // `fill` is the default role of a symbol colour, so it is omitted from the
  // variable name: wellKind.production.fill -> `--well-kind-production`.
  const tail = path.at(-1) === 'fill' ? path.slice(0, -1) : path;
  return `--${[groupPrefix[group], ...tail.map(kebabCase)].join('-')}`;
}

/**
 * CSS variable name of a domain token.
 *
 * @example domainTokenVar('curves.GR') // '--curve-gr'
 * @example domainTokenVar('wellKind.production.fill') // '--well-kind-production'
 * @example domainTokenVar('plan.sectionLine') // '--plan-section-line'
 */
export function domainTokenVar(path: DomainTokenPath): string {
  const [group, ...rest] = path.split('.');
  return varName(group as keyof DomainTokens, rest);
}

/**
 * Every domain token flattened to `{ '--curve-gr': '#2e7d32', … }`.
 * Used by `scripts/build-tokens.mjs` to generate `src/styles/domain.css`
 * and by its test to prove the generated file is in sync.
 */
export function flattenDomainTokens(): Record<string, string> {
  const result: Record<string, string> = {};

  const walk = (group: keyof DomainTokens, node: unknown, path: readonly string[]): void => {
    if (typeof node === 'string') {
      result[varName(group, path)] = node;
      return;
    }
    for (const [key, child] of Object.entries(node as Record<string, unknown>)) {
      walk(group, child, [...path, key]);
    }
  };

  for (const [group, node] of Object.entries(domainTokens)) {
    walk(group as keyof DomainTokens, node, []);
  }

  return result;
}
