import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { SessionContext } from '../../entities/session/model/sessionContext'
import { defaultPersona, userPersonas } from '../../entities/session/model/personas'
import { demoDatabase } from '../../repository/demo/demoDatabase'
import { primaryWell } from '../../repository/data/wells'
import { fetchWell } from '../../repository/api'
import { WellEditorPage } from './NewWellPage'

const blocker = vi.fn()
vi.mock('@tanstack/react-router', () => ({ useBlocker: (options: unknown) => blocker(options) }))

function renderWorkbench(readOnly = false, wellId?: string) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })
  const onSaved = vi.fn()
  render(<QueryClientProvider client={client}><SessionContext.Provider value={{ status: 'authenticated', persona: readOnly ? userPersonas.find((item) => item.id === 'admin.ai')! : defaultPersona, signIn: () => defaultPersona, signOut: vi.fn(), switchPersona: vi.fn() }}><WellEditorPage depositId="DEP-SARYTAU" wellId={wellId} onCancel={vi.fn()} onSaved={onSaved} /></SessionContext.Provider></QueryClientProvider>)
  return onSaved
}

describe('BGD object → section → workspace', () => {
  beforeEach(async () => { await demoDatabase.reset(); blocker.mockClear() })
  afterEach(async () => { cleanup(); vi.unstubAllGlobals(); await demoDatabase.reset() })

  it('edits impermeable intervals in a compact table and persists added and removed rows', async () => {
    const onSaved = renderWorkbench(false, primaryWell.id)
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Геологические условия' }))
    expect(screen.getByLabelText('Геологические осложнения')).toHaveValue(primaryWell.bgd!.geology.complications)
    fireEvent.click(screen.getByRole('tab', { name: 'Непроницаемые интервалы' }))
    expect(screen.getByRole('table', { name: 'Непроницаемые интервалы' })).toBeInTheDocument()
    fireEvent.change(screen.getByRole('spinbutton', { name: 'Непроницаемый интервал 1: От, м' }), { target: { value: '51' } })
    fireEvent.click(screen.getByRole('button', { name: 'Добавить интервал' }))
    expect(screen.getByRole('spinbutton', { name: 'Непроницаемый интервал 4: От, м' })).toHaveFocus()
    fireEvent.change(screen.getByRole('spinbutton', { name: 'Непроницаемый интервал 4: От, м' }), { target: { value: '500' } })
    fireEvent.change(screen.getByRole('spinbutton', { name: 'Непроницаемый интервал 4: До, м' }), { target: { value: '510' } })
    fireEvent.click(screen.getByRole('button', { name: 'Удалить непроницаемый интервал 2' }))
    expect(screen.getByRole('spinbutton', { name: 'Непроницаемый интервал 2: От, м' })).toHaveValue(340)
    fireEvent.click(screen.getByRole('tab', { name: 'Условия и уровни' }))
    expect(screen.getByRole('dialog', { name: 'Есть несохранённые изменения' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Остаться' }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить изменения' }))
    await waitFor(() => expect(onSaved).toHaveBeenCalledTimes(1))
    const saved = await fetchWell(primaryWell.id)
    expect(saved.bgd?.geology.impermeableIntervals.map(({ depthFrom, depthTo }) => [depthFrom, depthTo])).toEqual([[51, 67], [340, 352], [500, 510]])
  })

  it('keeps a legacy occurrence selected after consolidation into the deposit list', async () => {
    renderWorkbench(false, primaryWell.id)
    const selector = await screen.findByLabelText('Залежь')
    expect(screen.queryByRole('button', { name: 'Отмена' })).not.toBeInTheDocument()
    expect(screen.getByRole('status')).toHaveTextContent('Нет несохранённых изменений')
    expect(screen.getByRole('status').closest('footer')).toHaveAttribute('data-state', 'idle')
    expect(selector).toHaveValue('OCC-SARYTAU-01')
    expect(screen.getAllByRole('option', { name: 'PR-07' }).length).toBeGreaterThan(0)
    fireEvent.change(screen.getByLabelText('Месторождение *'), { target: { value: 'DEP-SEVERNOE' } })
    expect(screen.getByRole('status')).toHaveTextContent('Изменения готовы к сохранению')
    expect(screen.getByRole('status').closest('footer')).toHaveAttribute('data-state', 'ready')
    expect(selector).toHaveValue('')
  })

  it('guards both inner tabs and sections, saves before continuing and discards explicitly', async () => {
    const onSaved = renderWorkbench(false, primaryWell.id)
    fireEvent.change(await screen.findByLabelText('Название скважины *'), { target: { value: '2199' } })
    fireEvent.click(screen.getByRole('tab', { name: 'Описание и примечание' }))
    expect(screen.getByRole('dialog', { name: 'Есть несохранённые изменения' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Остаться' }))
    expect(screen.getByLabelText('Название скважины *')).toHaveValue(2199)
    fireEvent.click(screen.getByRole('tab', { name: 'Описание и примечание' }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await screen.findByLabelText('Примечание')
    expect(onSaved).not.toHaveBeenCalled()
    fireEvent.change(screen.getByLabelText('Примечание'), { target: { value: 'Discard this draft' } })
    fireEvent.click(screen.getByRole('button', { name: 'Паспорт' }))
    fireEvent.click(screen.getByRole('button', { name: 'Отменить изменения и перейти' }))
    expect(screen.getByLabelText('Паспорт составил')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Описание' }))
    expect(screen.getByLabelText('Название скважины *')).toHaveValue(2199)
    fireEvent.click(screen.getByRole('tab', { name: 'Описание и примечание' }))
    expect(screen.getByLabelText('Примечание')).not.toHaveValue('Discard this draft')
  })

  it('keeps the current tab when saving fails validation', async () => {
    renderWorkbench(false, primaryWell.id)
    fireEvent.change(await screen.findByLabelText('Название скважины *'), { target: { value: '' } })
    fireEvent.click(screen.getByRole('button', { name: 'Паспорт' }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await waitFor(() => expect(screen.getByRole('button', { name: 'Остаться' })).toBeEnabled())
    expect(screen.getByRole('dialog')).toHaveTextContent('Название скважины')
    expect(screen.getByLabelText('Название скважины *')).toBeInTheDocument()
    expect(screen.queryByLabelText('Паспорт составил')).not.toBeInTheDocument()
  })

  it('preserves read-only permissions in the new passport and coordinate sections', async () => {
    renderWorkbench(true)
    expect(await screen.findByLabelText('Название скважины *')).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Паспорт' }))
    expect(screen.getByLabelText('Паспорт составил')).toBeDisabled()
    fireEvent.click(screen.getByRole('button', { name: 'Координаты и глубина' }))
    expect(screen.getByRole('button', { name: 'Рассчитать координаты забоя' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Создать скважину' })).toBeDisabled()
  })

  it('keeps a scientific draft on Stay and only discards it after explicit confirmation', async () => {
    renderWorkbench(false, primaryWell.id)
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Литология' }))
    fireEvent.change(await screen.findByLabelText('Порода'), { target: { value: 'Глина' } })
    fireEvent.click(screen.getByRole('button', { name: 'Паспорт' }))
    expect(screen.getByRole('dialog', { name: 'Есть несохранённые изменения' })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Остаться' })).toHaveFocus()
    expect(screen.queryByText('Литологическая колонка')).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Остаться' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByLabelText('Порода')).toHaveValue('Глина')
    fireEvent.click(screen.getByRole('button', { name: 'Паспорт' }))
    fireEvent.click(screen.getByRole('button', { name: 'Отменить изменения и перейти' }))
    expect(screen.getByLabelText('Паспорт составил')).toBeInTheDocument()
    expect(screen.queryByLabelText('Порода')).not.toBeInTheDocument()
  })

  it('saves lithology before changing an inner view and protects invalid boundaries', async () => {
    renderWorkbench(false, primaryWell.id)
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Литология' }))
    fireEvent.change(await screen.findByLabelText('Порода'), { target: { value: 'Глина' } })
    fireEvent.click(screen.getByRole('tab', { name: /По каротажу/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByRole('tab', { name: /По каротажу/ })).toHaveAttribute('aria-selected', 'true')
    fireEvent.click(screen.getByRole('tab', { name: /По керну/ }))
    expect(screen.getByLabelText('Порода')).toHaveValue('Глина')
    fireEvent.change(screen.getByLabelText('Конечная глубина'), { target: { value: '-1' } })
    fireEvent.click(screen.getByRole('button', { name: 'Керновые рейсы и промер' }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await waitFor(() => expect(screen.getByRole('dialog')).toHaveTextContent('Проверьте поля'))
    expect(screen.getByLabelText('Конечная глубина')).toHaveValue(-1)
    fireEvent.click(screen.getByRole('button', { name: 'Отменить изменения и перейти' }))
    expect(await screen.findByRole('tab', { name: 'Керновые рейсы' })).toHaveAttribute('aria-selected', 'true')
  })

  it('protects un-applied ore fields when switching inner tabs and saves them before continuing', async () => {
    renderWorkbench(false, primaryWell.id)
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Рудные интервалы' }))
    fireEvent.change(await screen.findByLabelText('Содержание, % *'), { target: { value: '0.1234' } })
    fireEvent.click(screen.getByRole('tab', { name: /Рудные объединения/ }))
    expect(screen.getByRole('dialog')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByRole('tab', { name: /Рудные объединения/ })).toHaveAttribute('aria-selected', 'true')
    fireEvent.click(screen.getByRole('tab', { name: /Рудные интервалы/ }))
    expect(screen.getByLabelText('Содержание, % *')).toHaveValue(.1234)
    fireEvent.change(screen.getByLabelText('Содержание, % *'), { target: { value: '0.4321' } })
    fireEvent.click(screen.getByRole('tab', { name: /Рудные объединения/ }))
    fireEvent.click(screen.getByRole('button', { name: 'Отменить изменения и перейти' }))
    fireEvent.click(screen.getByRole('tab', { name: /Рудные интервалы/ }))
    expect(screen.getByLabelText('Содержание, % *')).toHaveValue(.1234)
  })

  it('blocks switching wells and any URL tab or view change while a form is dirty', async () => {
    renderWorkbench(false, primaryWell.id)
    fireEvent.change(await screen.findByLabelText('Название скважины *'), { target: { value: '2999' } })
    const guard = blocker.mock.calls.at(-1)![0]
    const current = { pathname: '/geology/bgd/DEP-SARYTAU/wells/WELL-1042', search: { tab: 'description' } }
    expect(guard.shouldBlockFn({ current, next: { ...current, pathname: '/geology/bgd/DEP-SARYTAU/wells/WELL-1014' } })).toBe(true)
    expect(guard.shouldBlockFn({ current, next: { ...current, search: { tab: 'passport' } } })).toBe(true)
    expect(guard.shouldBlockFn({ current, next: { ...current, search: { tab: 'description', view: 'notes' } } })).toBe(true)
    expect(guard.shouldBlockFn({ current, next: current })).toBe(false)
  })

  it('starts with a compact section menu on a phone and keeps the form accessible', async () => {
    vi.stubGlobal('matchMedia', () => ({ matches: true }))
    renderWorkbench()
    expect(await screen.findByLabelText('Название скважины *')).toBeEnabled()
    const expand = screen.getByRole('button', { name: 'Развернуть разделы скважины' })
    expect(expand).toHaveAttribute('aria-expanded', 'false')
    expect(screen.queryByRole('button', { name: 'Паспорт' })).not.toBeInTheDocument()
    fireEvent.click(expand)
    fireEvent.click(screen.getByRole('button', { name: 'Паспорт' }))
    expect(screen.getByLabelText('Паспорт составил')).toBeEnabled()
    fireEvent.click(screen.getByRole('button', { name: 'Свернуть разделы скважины' }))
    expect(screen.getByLabelText('Паспорт составил')).toBeEnabled()
  })

  it('adds interval batches, preserves filled rows when removing blanks, and saves all five fields', async () => {
    const onSaved = renderWorkbench()
    fireEvent.change(await screen.findByLabelText('Название скважины *'), { target: { value: '2299' } })
    fireEvent.click(screen.getByRole('button', { name: 'Проходка и освоение' }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await screen.findByRole('button', { name: 'Добавить интервалы' })
    for (const count of [1, 5, 10, 20]) {
      const before = screen.queryAllByRole('spinbutton', { name: /Интервал .*Диаметр/ }).length
      fireEvent.click(screen.getByRole('button', { name: 'Добавить интервалы' }))
      fireEvent.click(screen.getByRole('menuitem', { name: count === 1 ? '1 интервал' : `${count} интервалов` }))
      expect(screen.getAllByRole('spinbutton', { name: /Интервал .*Диаметр/ })).toHaveLength(before + count)
      expect(screen.getByRole('spinbutton', { name: `Интервал ${before + 1}: Диаметр, мм` })).toHaveFocus()
    }
    fireEvent.change(screen.getByLabelText('Интервал 1: Диаметр, мм'), { target: { value: '190' } })
    fireEvent.change(screen.getByLabelText('Интервал 1: От, м'), { target: { value: '0' } })
    fireEvent.change(screen.getByLabelText('Интервал 1: До, м'), { target: { value: '25' } })
    fireEvent.change(screen.getByLabelText('Интервал 1: Породоразрушающий инструмент'), { target: { value: 'Алмазная коронка' } })
    fireEvent.change(screen.getByLabelText('Интервал 1: Очистной агент'), { target: { value: 'Техническая вода' } })
    fireEvent.change(screen.getByLabelText('Интервал 3: Очистной агент'), { target: { value: 'Сульфанол' } })
    fireEvent.click(screen.getByRole('button', { name: 'Удалить интервал 2' }))
    fireEvent.click(screen.getByRole('button', { name: /Удалить пустые/ }))
    expect(screen.getAllByRole('spinbutton', { name: /Интервал .*Диаметр/ })).toHaveLength(2)
    expect(screen.getByLabelText('Интервал 2: Очистной агент')).toHaveValue('Сульфанол')
    fireEvent.click(screen.getByRole('button', { name: 'Удалить интервал 2' }))
    fireEvent.click(screen.getByRole('button', { name: 'Описание' }))
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить и перейти' }))
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Проходка и освоение' }))
    expect(screen.getByLabelText('Интервал 1: Диаметр, мм')).toHaveValue(190)
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить изменения' }))
    await waitFor(() => expect(onSaved).toHaveBeenCalled())
    expect(onSaved.mock.calls[0]?.[0].bgd.drilling.intervals).toEqual([
      expect.objectContaining({ drillingDiameter: 190, depthFrom: 0, depthTo: 25, drillingTool: 'Алмазная коронка', flushingAgent: 'Техническая вода' }),
    ])
  })

  it('supports the batch menu keyboard and disables interval changes without edit permission', async () => {
    renderWorkbench()
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Проходка и освоение' }))
    const trigger = screen.getByRole('button', { name: 'Добавить интервалы' })
    fireEvent.click(trigger)
    expect(screen.getByRole('menuitem', { name: '1 интервал' })).toHaveFocus()
    fireEvent.keyDown(document.activeElement!, { key: 'End' })
    expect(screen.getByRole('menuitem', { name: '20 интервалов' })).toHaveFocus()
    fireEvent.keyDown(document.activeElement!, { key: 'Escape' })
    expect(trigger).toHaveFocus()
    expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    cleanup()
    renderWorkbench(true, primaryWell.id)
    await screen.findByLabelText('Название скважины *')
    fireEvent.click(screen.getByRole('button', { name: 'Проходка и освоение' }))
    expect(screen.getByRole('button', { name: 'Добавить интервалы' })).toBeDisabled()
    expect(screen.getByRole('button', { name: /Удалить пустые/ })).toBeDisabled()
    expect(screen.getByLabelText('Интервал 1: Диаметр, мм')).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Удалить интервал 1' })).toBeDisabled()
  })
})
