import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { defaultPersona } from '../../entities/session/model/personas'
import { SessionContext } from '../../entities/session/model/sessionContext'
import * as api from '../../repository/api'
import { demoDatabase } from '../../repository/demo/demoDatabase'
import { GeologyDatabaseDeposit } from './GeologyDatabaseDeposit'

const onOpenDeposit = vi.fn()

function mount(depositId = 'DEP-SARYTAU', readOnly = false, admin = false) {
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  const persona = admin ? { ...defaultPersona, roles: ['R13' as const] } : readOnly ? { ...defaultPersona, roles: ['R3' as const] } : defaultPersona
  return render(<QueryClientProvider client={client}><SessionContext.Provider value={{ status: 'authenticated', persona, signIn: () => persona, signOut: vi.fn(), switchPersona: vi.fn() }}>
    <GeologyDatabaseDeposit depositId={depositId} onOpenDeposit={onOpenDeposit} onDeleted={vi.fn()} />
  </SessionContext.Provider></QueryClientProvider>)
}

describe('Deposit condition limits', () => {
  beforeEach(async () => { onOpenDeposit.mockReset(); await demoDatabase.reset() })
  afterEach(async () => { cleanup(); vi.restoreAllMocks(); await demoDatabase.reset() })

  it('opens one editable deposit set, saves and closes, then reloads without approval or versions', async () => {
    const confirm = vi.spyOn(window, 'confirm')
    const view = mount()
    const open = await screen.findByRole('button', { name: 'Изменить' })
    expect(screen.getAllByRole('button', { name: 'Изменить' })).toHaveLength(1)
    open.focus()
    fireEvent.click(open)
    const dialog = screen.getByRole('dialog', { name: 'Кондиционные лимиты Сарытау' })
    expect(within(dialog).getAllByRole('textbox')).toHaveLength(28)
    expect(within(dialog).queryByText(/мерзлот/)).not.toBeInTheDocument()
    expect(within(dialog).getAllByRole('button').map((button) => button.textContent)).toEqual(['Сохранить', 'Отменить'])
    const cutoff = within(dialog).getByLabelText('Бортовое содержание урана')
    expect(cutoff).toBeEnabled()
    expect(within(dialog).getByLabelText('Верхняя высота разрезов по умолчанию')).toHaveFocus()
    fireEvent.change(cutoff, { target: { value: '0.025' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(open).toHaveFocus()
    expect(confirm).not.toHaveBeenCalled()
    view.unmount()
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Изменить' }))
    expect(screen.getByLabelText('Бортовое содержание урана')).toHaveValue('0.025')
    expect(screen.getByLabelText('Бортовое содержание урана')).toBeEnabled()
    expect((await api.fetchGeologicalMasterData()).conditionSets.filter((item) => item.depositId === 'DEP-SARYTAU')).toHaveLength(1)
  })

  it('cancels edits without a confirmation and restores stored values on reopening', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Изменить' }))
    fireEvent.change(screen.getByLabelText('Бортовое содержание урана'), { target: { value: 'discard me' } })
    fireEvent.click(screen.getByRole('button', { name: 'Отменить' }))
    fireEvent.click(screen.getByRole('button', { name: 'Изменить' }))
    expect(screen.getByLabelText('Бортовое содержание урана')).toHaveValue('0.012')
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('allows a deposit without sites to save its first and only set', async () => {
    mount('DEP-SEVERNOE', false, true)
    fireEvent.click(await screen.findByRole('button', { name: 'Изменить' }))
    expect(screen.getByRole('dialog', { name: 'Кондиционные лимиты Северное' })).toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('Бортовое содержание урана'), { target: { value: '0.02' } })
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    fireEvent.click(screen.getByRole('button', { name: 'Изменить' }))
    expect(screen.getByLabelText('Бортовое содержание урана')).toHaveValue('0.02')
    expect((await api.fetchGeologicalMasterData()).conditionSets.filter((item) => item.depositId === 'DEP-SEVERNOE')).toHaveLength(1)
  })

  it('preserves edits and shows the save error inside the open form', async () => {
    vi.spyOn(api, 'saveConditionSet').mockRejectedValueOnce(new Error('Не удалось сохранить лимиты.'))
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Изменить' }))
    fireEvent.change(screen.getByLabelText('Бортовое содержание урана'), { target: { value: '0.03' } })
    fireEvent.click(screen.getByRole('button', { name: 'Сохранить' }))
    const dialog = screen.getByRole('dialog')
    expect(await within(dialog).findByRole('alert')).toHaveTextContent('Не удалось сохранить лимиты.')
    expect(screen.getByLabelText('Бортовое содержание урана')).toHaveValue('0.03')
    expect(screen.getByRole('button', { name: 'Сохранить' })).toBeEnabled()
  })

  it('keeps the form read-only without an edit permission', async () => {
    mount('DEP-SARYTAU', true)
    fireEvent.click(await screen.findByRole('button', { name: 'Изменить' }))
    expect(screen.getByLabelText('Бортовое содержание урана')).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Сохранить' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Отменить' })).toBeEnabled()
  })

  it('shows every deposit section together, including multilingual descriptions and occurrences', async () => {
    mount()
    expect(await screen.findByRole('heading', { name: 'Названия и описание' })).toBeVisible()
    expect(screen.getByText('Урановое месторождение Сарытау.')).toBeVisible()
    expect(screen.getByText('Сарытау уран кен орны.')).toBeVisible()
    expect(screen.getByText('Sarytau uranium deposit.')).toBeVisible()
    expect(screen.getByRole('heading', { name: 'Участки' })).toBeVisible()
    expect(screen.getByRole('heading', { name: 'Список залежей' })).toBeVisible()
    expect(screen.getByRole('heading', { name: 'Кондиционные лимиты Сарытау' })).toBeVisible()
    expect(screen.getByText('Бортовое содержание урана')).toBeVisible()
    expect(screen.queryByRole('heading', { name: 'Скважины' })).not.toBeInTheDocument()
    expect(screen.queryByRole('tablist')).not.toBeInTheDocument()
    const facts = screen.getByRole('heading', { name: 'Сведения об объекте' }).closest('section')!
    expect(within(facts).queryByText(/Статус|Создано|Изменено|Версия карточки/)).not.toBeInTheDocument()
    expect(screen.getByRole('table', { name: 'Участки' })).toBeVisible()
    expect(screen.getByRole('table', { name: 'Залежи' })).toBeVisible()
  })

  it('edits deposit data from the header and updates the unified view after saving', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Редактировать' }))
    const dialog = screen.getByRole('dialog', { name: 'Редактирование месторождения Сарытау' })
    expect(within(dialog).queryByRole('button', { name: 'Добавить залежь' })).not.toBeInTheDocument()
    expect(within(dialog).queryByText('Список залежей')).not.toBeInTheDocument()
    expect(dialog.querySelector('.panel')).toBeNull()
    fireEvent.change(within(dialog).getByLabelText('Описание (EN)'), { target: { value: 'Updated deposit description.' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить изменения' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.getByText('Updated deposit description.')).toBeVisible()
    expect((await api.fetchGeologicalMasterData()).deposits.find((item) => item.id === 'DEP-SARYTAU')?.descriptionEn).toBe('Updated deposit description.')
    expect((await api.fetchGeologicalMasterData()).deposits.find((item) => item.id === 'DEP-SARYTAU')?.occurrences).toHaveLength(2)
  })

  it('adds, edits and deletes a site from its independent table', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Добавить участок' }))
    let dialog = screen.getByRole('dialog', { name: 'Добавить участок' })
    fireEvent.change(within(dialog).getByLabelText(/Код участка/), { target: { value: 'SOUTH' } })
    fireEvent.change(within(dialog).getByLabelText('Наименование участка'), { target: { value: 'Южный' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    fireEvent.click(screen.getByRole('button', { name: 'Действия: участок Южный' }))
    const menu = screen.getByRole('menu')
    expect(within(menu).getByRole('menuitem', { name: 'Редактировать' })).toHaveFocus()
    fireEvent.click(within(menu).getByRole('menuitem', { name: 'Редактировать' }))
    dialog = screen.getByRole('dialog', { name: 'Редактирование участка' })
    expect(within(dialog).getByLabelText(/Код участка/)).toBeDisabled()
    fireEvent.change(within(dialog).getByLabelText('Наименование участка'), { target: { value: 'Южный обновлённый' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    fireEvent.click(screen.getByRole('button', { name: 'Действия: участок Южный обновлённый' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Удалить' }))
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Удалить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.queryByRole('button', { name: 'Действия: участок Южный обновлённый' })).not.toBeInTheDocument()
    expect((await api.fetchGeologicalMasterData()).deposits.find((item) => item.id === 'DEP-SARYTAU')?.occurrences).toHaveLength(2)
  })

  it('manages occurrences separately and preserves entered values after a duplicate error', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Добавить залежь' }))
    let dialog = screen.getByRole('dialog', { name: 'Добавить залежь' })
    expect(within(dialog).getByRole('combobox', { name: 'Тип залежи' })).toHaveValue('Рудная залежь')
    expect(within(dialog).getAllByRole('option').map((option) => option.textContent)).toEqual(expect.arrayContaining(['Рудная залежь', 'Участок', 'Площадь']))
    for (const locale of ['RU', 'KZ', 'EN']) fireEvent.change(within(dialog).getByLabelText(`Название (${locale})`), { target: { value: 'PR-07' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить' }))
    expect(await within(dialog).findByRole('alert')).toHaveTextContent('дубликат')
    expect(within(dialog).getByLabelText('Название (RU)')).toHaveValue('PR-07')
    for (const locale of ['RU', 'KZ', 'EN']) fireEvent.change(within(dialog).getByLabelText(`Название (${locale})`), { target: { value: 'NEW-01' } })
    fireEvent.change(within(dialog).getByRole('combobox', { name: 'Тип залежи' }), { target: { value: 'Участок' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    fireEvent.click(screen.getByRole('button', { name: 'Действия: залежь NEW-01' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Редактировать' }))
    dialog = screen.getByRole('dialog', { name: 'Редактирование залежи' })
    expect(within(dialog).getByRole('combobox', { name: 'Тип залежи' })).toHaveValue('Участок')
    expect(within(dialog).getAllByRole('option').map((option) => option.textContent)).toEqual(expect.arrayContaining(['Рудная залежь', 'Участок', 'Площадь']))
    fireEvent.change(within(dialog).getByRole('combobox', { name: 'Тип залежи' }), { target: { value: 'Площадь' } })
    fireEvent.change(within(dialog).getByLabelText('Название (EN)'), { target: { value: 'New occurrence' } })
    fireEvent.click(within(dialog).getByRole('button', { name: 'Сохранить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(within(screen.getByRole('table', { name: 'Залежи' })).getByText('New occurrence')).toBeVisible()
    expect(within(screen.getByRole('table', { name: 'Залежи' })).getByText('Площадь')).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: 'Действия: залежь NEW-01' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Удалить' }))
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: 'Удалить' }))
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument())
    expect(screen.queryByRole('button', { name: 'Действия: залежь NEW-01' })).not.toBeInTheDocument()
  })

  it('dismisses row actions with the keyboard and retains used occurrences after a deletion failure', async () => {
    mount()
    const trigger = await screen.findByRole('button', { name: 'Действия: залежь PR-07' })
    fireEvent.keyDown(trigger, { key: 'ArrowDown' })
    fireEvent.keyDown(screen.getByRole('menu'), { key: 'End' })
    expect(screen.getByRole('menuitem', { name: 'Удалить' })).toHaveFocus()
    fireEvent.keyDown(screen.getByRole('menu'), { key: 'Escape' })
    expect(trigger).toHaveFocus()
    expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    fireEvent.click(trigger)
    fireEvent.click(screen.getByRole('menuitem', { name: 'Удалить' }))
    const dialog = screen.getByRole('dialog')
    fireEvent.click(within(dialog).getByRole('button', { name: 'Удалить' }))
    expect(await within(dialog).findByRole('alert')).toHaveTextContent('используется скважинами')
    fireEvent.click(within(dialog).getByRole('button', { name: 'Отменить' }))
    expect(screen.getByRole('button', { name: 'Действия: залежь PR-07' })).toBeInTheDocument()
  })

  it('switches deposits from the header, saves the preference and excludes hidden entries', async () => {
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Сменить месторождение' }))
    const dialog = screen.getByRole('dialog', { name: 'Сменить месторождение' })
    expect(within(dialog).queryByRole('button', { name: /Восточная/ })).not.toBeInTheDocument()
    fireEvent.click(within(dialog).getByRole('button', { name: /Северное/ }))
    await waitFor(() => expect(onOpenDeposit).toHaveBeenCalledWith('DEP-SEVERNOE'))
    expect((await api.fetchPlatformPreferences()).currentDepositId).toBe('DEP-SEVERNOE')
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('keeps the current deposit and shows a switching failure without navigation', async () => {
    vi.spyOn(api, 'savePlatformPreferences').mockRejectedValueOnce(new Error('Настройки не сохранены.'))
    mount()
    fireEvent.click(await screen.findByRole('button', { name: 'Сменить месторождение' }))
    const dialog = screen.getByRole('dialog', { name: 'Сменить месторождение' })
    fireEvent.click(within(dialog).getByRole('button', { name: /Северное/ }))
    expect(await within(dialog).findByRole('alert')).toHaveTextContent('Настройки не сохранены.')
    expect(onOpenDeposit).not.toHaveBeenCalled()
    expect((await api.fetchPlatformPreferences()).currentDepositId).toBe('DEP-SARYTAU')
    fireEvent.click(within(dialog).getByRole('button', { name: 'Отменить' }))
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('shows audit in the same view only with permission and omits editing for readers', async () => {
    const view = mount('DEP-SARYTAU', false, true)
    expect(await screen.findByRole('heading', { name: 'Аудит месторождения' })).toBeVisible()
    view.unmount()
    mount('DEP-SARYTAU', true)
    expect(await screen.findByRole('button', { name: 'Сменить месторождение' })).toBeEnabled()
    expect(screen.queryByRole('button', { name: 'Редактировать' })).not.toBeInTheDocument()
    expect(screen.queryByRole('heading', { name: 'Аудит месторождения' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Действия:/ })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Добавить участок|Добавить залежь/ })).not.toBeInTheDocument()
  })
})
