import { Link } from '@tanstack/react-router'
import { FileDown, Send, TrendingDown, TrendingUp } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '../../shared/ui/Badge'
import { PageHeader } from '../../shared/ui/PageHeader'
import { Panel } from '../../shared/ui/Panel'

const metrics = [{ name: 'Подача раствора, м³', plan: 1280, fact: 1248, unit: 'м³', direction: 'down' }, { name: 'Расход кислоты, т', plan: 12.4, fact: 11.6, unit: 'т', direction: 'down' }, { name: 'Приемистость WELL-1042, м³/ч', plan: 82, fact: 79, unit: 'м³/ч', direction: 'down' }, { name: 'Закрытие пакета замеров', plan: 100, fact: 100, unit: '%', direction: 'up' }]
export function PlanFactPage() {
  const [published, setPublished] = useState(false)
  return <div className="page-stack"><PageHeader eyebrow="Технологический модуль · TECH-20–21" title="План‑факт и суточный отчёт" description="Срез BLK-07-12 за 10 августа. Факт собран из опубликованных источников с сохранением происхождения данных." meta={<Badge tone={published ? 'success' : 'warning'} dot>{published ? 'Отчёт опубликован · rev.2' : 'Черновик отчёта · rev.2'}</Badge>} actions={<Link to="/technology" className="button button--secondary button--md">К обзору</Link>} />
    <div className="planfact-layout"><Panel title="План‑факт" description="План v3.1 · фактические данные на 20:00"><div className="planfact-table"><div className="planfact-table__head"><span>Показатель</span><span>План</span><span>Факт</span><span>Отклонение</span><span>Источник</span></div>{metrics.map((metric) => { const diff = metric.fact - metric.plan; return <div className="planfact-table__row" key={metric.name}><span><strong>{metric.name}</strong></span><span>{metric.plan} {metric.unit}</span><span>{metric.fact} {metric.unit}</span><span className={diff < 0 ? 'is-negative' : 'is-positive'}>{diff < 0 ? <TrendingDown size={15} /> : <TrendingUp size={15} />}{diff > 0 ? '+' : ''}{diff} {metric.unit}</span><span>{metric.name.includes('Приемистость') ? 'РВР-042' : metric.name.includes('Пакета') ? 'S-2026-08-10-02' : 'Balance v1.0'}</span></div>})}</div></Panel><aside className="planfact-aside"><Panel title="Суточный отчёт" description="Форма OP-DAY-03 · snapshot 20:00"><div className="report-summary"><div><Badge tone="warning">1 отклонение</Badge><span>DEV-042: небаланс раствора 4,8%.</span></div><div><Badge tone="success">РВР partial</Badge><span>Приемистость: 79 м³/ч, monitoring назначен.</span></div><div><Badge tone="ai">Поздняя лаборатория</Badge><span>SOL-0822 вошла в revision 2.</span></div></div><div className="report-actions"><button type="button" className="button button--secondary button--md"><FileDown size={16} />Preview PDF</button><button type="button" className="button button--primary button--md" disabled={published} onClick={() => setPublished(true)}><Send size={16} />{published ? 'Опубликовано' : 'Опубликовать'}</button></div></Panel><Panel title="Audit trail" description="Версии отчёта"><div className="delivery-audit"><div><span><strong>20:05</strong> Revision 2 пересчитан после SOL-0822.</span></div>{published && <div><span><strong>Сейчас</strong> Отчёт опубликован для руководителя и аналитики.</span></div>}</div></Panel></aside></div>
  </div>
}
