import { Link } from '@tanstack/react-router'
import { Bot, CheckCircle2, Eye, ThumbsDown, ThumbsUp } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '../../shared/ui/Badge'
import { PageHeader } from '../../shared/ui/PageHeader'
import { Panel } from '../../shared/ui/Panel'

export function RecommendationsPage() {
  const [decision, setDecision] = useState<'none' | 'accepted' | 'rejected'>('none')
  return <div className="page-stack"><PageHeader eyebrow="Технологический модуль · TECH-22" title="AI-рекомендация по отклонению" description="DEV-042: рекомендация только объясняет возможное действие. Она не меняет технологический режим и не создаёт утверждённый наряд без решения специалиста." meta={<Badge tone="ai" dot>Модель anomaly-ranking v0.8 · confidence 78%</Badge>} actions={<Link to="/technology/balance" className="button button--secondary button--md">К балансу</Link>} />
    <div className="recommendation-layout"><Panel title="Рекомендация" description="На основе сменных замеров, лаборатории и РВР-042"><div className="recommendation-main"><Bot size={28} /><div><strong>Провести повторный замер приемистости WELL-1042 после завершения РВР.</strong><span>Причина: небаланс 4,8%, падение pH и partial-эффект РВР не позволяют подтвердить восстановление режима.</span></div></div><div className="recommendation-evidence"><div><span>Evidence</span><strong>S-2026-08-10-02 · SOL-0822 · DEV-042 · РВР-042</strong></div><div><span>Ограничение</span><strong>Не изменять расход кислоты без review технолога.</strong></div><div><span>Период</span><strong>10 августа, 08:00–20:00 · данные до 20:05</strong></div></div></Panel><aside className="recommendation-aside"><Panel title="Решение технолога" description="Действие фиксируется в audit trail"><div className="recommendation-actions"><button type="button" className={decision === 'accepted' ? 'is-selected' : ''} onClick={() => setDecision('accepted')}><ThumbsUp size={18} />Принять и создать задачу</button><button type="button" className={decision === 'rejected' ? 'is-selected' : ''} onClick={() => setDecision('rejected')}><ThumbsDown size={18} />Отклонить рекомендацию</button>{decision !== 'none' && <div className="recommendation-result"><CheckCircle2 size={17} /><span>{decision === 'accepted' ? 'Задача TECH-TASK-128 создана для диспетчера.' : 'Решение отклонено: остаётся ручной мониторинг.'}</span></div>}</div></Panel><Panel title="Похожие сигналы" description="Доступны в пределах scope"><div className="correlation-checks"><div><Badge tone="warning">02 авг.</Badge><span>WELL-1038: падение приемистости после снижения pH.</span></div><div><Badge tone="success">05 авг.</Badge><span>Повторный замер подтвердил нормализацию без РВР.</span></div></div><Link to="/technology/plan-fact" className="text-link"><Eye size={15} />Открыть план‑факт</Link></Panel></aside></div>
  </div>
}
