import { Link } from '@tanstack/react-router'
import { Activity, AlertTriangle, Beaker, Bot, ClipboardCheck, Gauge, RadioTower, Scale } from 'lucide-react'
import { Badge } from '../../shared/ui/Badge'
import { MetricCard } from '../../shared/ui/MetricCard'
import { PageHeader } from '../../shared/ui/PageHeader'
import { Panel } from '../../shared/ui/Panel'

export function TechnologyPage() {
  return <div className="page-stack"><PageHeader eyebrow="Технологический модуль · TECH-01" title="Состояние участка" description="Оперативный контур BLK-07-12 на смену 10 августа: замеры, баланс, оборудование и работы РВР." meta={<Badge tone="warning" dot>Смена 08:00–20:00 · 74% закрыто</Badge>} actions={<Link to="/technology/measurements" className="button button--primary button--md"><ClipboardCheck size={17} />Открыть замеры</Link>} />
    <div className="metrics-grid"><MetricCard icon={Gauge} label="Ожидаемые замеры" value="18 / 24" detail="3 требуют ввода до закрытия" tone="amber" /><MetricCard icon={Scale} label="Небаланс раствора" value="4,8%" detail="выше нормы 3,0%" tone="violet" /><MetricCard icon={Beaker} label="Лаборатория" value="2" detail="результата поступили поздно" tone="blue" /><MetricCard icon={AlertTriangle} label="Отклонения" value="3" detail="1 требует решения технолога" tone="amber" /></div>
    <div className="tech-overview-grid"><Panel title="Технологическая схема" description="Активная схема v4.2 · BLK-07-12" action={<Link to="/technology/balance" className="text-link">К балансу</Link>}><div className="tech-scheme"><div><Activity size={20} /><strong>Подача раствора</strong><span>1 248 м³/ч</span></div><i>→</i><div className="is-warning"><Beaker size={20} /><strong>Кислотный узел</strong><span>pH 2,8 · ниже плана</span></div><i>→</i><div><Gauge size={20} /><strong>Куст WELL-1042</strong><span>16 скважин в работе</span></div></div></Panel><Panel title="Требуют решения" description="Отклонения, влияющие на смену"><div className="attention-list"><Link to="/technology/balance" className="attention-item"><span className="well-type well-type--warning"><AlertTriangle size={16} /></span><span><strong>DEV-042 · небаланс раствора</strong><small>4,8% против порога 3,0%</small></span><Badge tone="warning">Новый</Badge></Link><Link to="/technology/measurements" className="attention-item"><span className="well-type well-type--injection"><ClipboardCheck size={16} /></span><span><strong>Пакет сменных замеров</strong><small>3 обязательных значения не введены</small></span><Badge tone="warning">Открыт</Badge></Link></div></Panel></div>
    <div className="module-shortcuts"><Link to="/technology/measurements" className="module-shortcut-link"><ClipboardCheck size={20} /><div><strong>Оперативные замеры</strong><span>Ввод, validation, источник и закрытие смены</span></div><Badge>TECH-06</Badge></Link><Link to="/technology/solutions" className="module-shortcut-link"><Beaker size={20} /><div><strong>Растворы и лаборатория</strong><span>Пробы, результат, QA/QC и поздние данные</span></div><Badge>TECH-07</Badge></Link><Link to="/technology/balance" className="module-shortcut-link"><Scale size={20} /><div><strong>Потоки и баланс</strong><span>Компоненты небаланса, evidence и действие технолога</span></div><Badge>TECH-10–12</Badge></Link><Link to="/technology/equipment" className="module-shortcut-link"><Activity size={20} /><div><strong>Оборудование</strong><span>Ресурс, риск, обслуживание и связь с РВР</span></div><Badge>TECH-13</Badge></Link><Link to="/technology/logs" className="module-shortcut-link"><RadioTower size={20} /><div><strong>Технологические ГИС</strong><span>Профиль режима и сравнение дат</span></div><Badge>TECH-20</Badge></Link><Link to="/technology/plan-fact" className="module-shortcut-link"><Scale size={20} /><div><strong>План‑факт и отчёты</strong><span>Версия плана, источники факта и публикация</span></div><Badge>TECH-21</Badge></Link><Link to="/technology/recommendations" className="module-shortcut-link"><Bot size={20} /><div><strong>AI-рекомендации</strong><span>Evidence, ограничения и решение технолога</span></div><Badge>TECH-22</Badge></Link></div>
  </div>
}
