import { useState } from 'react'
import type { CoreSegment, InterpretationDocument, InterpretationWell, LithologyInterval, SampleKind } from '../../../entities/interpretation/model/types'
import { deleteCore, derivedRuns, flipRun, hasMeasurement, insertNoCore, isNoCore, mappedSamples, mergeCore, moveCore, moveCoreContact, moveRun, resizeCore, restoreCore, sourceOf, splitCore, syncCore, transformCore } from '../../../entities/interpretation/lib/core'
import { mineralsOf } from '../../../entities/interpretation/lib/commands'
import { Button } from '../../../shared/ui/Button'
import { interpretationCopy as copy } from '../model/copy'
import { Field } from './Editors'

export function CoreOperationsEditor({ well, document, segment, disabled, onCommand, onDirty }:
  { well: InterpretationWell; document: InterpretationDocument; segment: CoreSegment; disabled: boolean; onCommand: (next: () => InterpretationDocument, notice: string) => void; onDirty: () => void }) {
  const source = sourceOf(well, segment), noCore = isNoCore(segment), measured = hasMeasurement(well, segment)
  const [from, setFrom] = useState(segment.from), [reversed, setReversed] = useState(segment.reversed)
  const [splitAt, setSplitAt] = useState((segment.from + segment.to) / 2), [size, setSize] = useState(segment.to - segment.from)
  const [anchor, setAnchor] = useState<'top' | 'bottom'>('top'), [insertSize, setInsertSize] = useState(1), [contact, setContact] = useState(segment.to)
  const base = segment.properties ?? source?.lithology.find(r => r.to > source.from && r.from < source.to) ?? { rock: 'unknown' as const, mineralization: '', note: '' }
  const [properties, setProperties] = useState<Omit<LithologyInterval, 'id' | 'from' | 'to'>>({ rock: base.rock, mineralization: base.mineralization, minerals: mineralsOf(base as LithologyInterval), note: base.note, color: noCore ? undefined : base.color })
  const updateProperties = (next: Partial<typeof properties>) => { setProperties(p => ({ ...p, ...next })); onDirty() }
  const run = derivedRuns(well, document).find(r => r.id === segment.runId)!
  const removed = segment.from === segment.to
  const sampleCount = mappedSamples(well, document).filter(s => s.segmentId === segment.id).length
  const change = (fn: () => InterpretationDocument, message: string) => onCommand(fn, message)
  return <div>
    <div className="interpretation-inspector__summary"><span>{noCore ? 'Бескерновый сегмент' : 'Керновый сегмент'}</span><strong>{segment.from.toFixed(1)} — {segment.to.toFixed(1)} м</strong><small>{source ? `По бурению: ${source.from.toFixed(1)}–${source.to.toFixed(1)} м` : segment.sourceFrom === undefined ? 'Вставлен · без исходной глубины' : `Исходный бескерновый: ${segment.sourceFrom}–${segment.sourceTo} м`}</small><small>{removed ? 'Удалён · доступно восстановление' : reversed ? 'Перевёрнут' : 'Прямая ориентация'}{segment.properties ? ' · свойства изменены' : ''}{source && Math.abs(source.to - source.from - (segment.to - segment.from)) > 0.001 ? ' · мощность изменена' : ''}</small></div>
    <fieldset disabled={disabled}>
      {!removed && <form onSubmit={e => { e.preventDefault(); change(() => transformCore(well, document, segment.id, from, reversed), 'Привязка и связанные данные изменены.') }}>
        <Field label="Начало в сводной колонке, м"><input required type="number" step="0.1" value={from} onChange={e => { setFrom(Number(e.target.value)); onDirty() }} /></Field>
        {!noCore && <label className="interpretation-check"><input type="checkbox" checked={reversed} onChange={e => { setReversed(e.target.checked); onDirty() }} />Перевернуть порядок керна</label>}
        <div className="interpretation-actions"><Button size="sm" type="submit">Применить привязку</Button></div>
      </form>}
      {removed ? <Button size="sm" onClick={() => change(() => restoreCore(well, document, segment.id), 'Исходный сегмент восстановлен вместе со связанными данными.')}>Восстановить сегмент</Button> : <>
        <div className="interpretation-actions"><Button variant="secondary" size="sm" onClick={() => change(() => moveCore(well, document, segment.id, 'above'), 'Сегменты переставлены.')}>Переставить выше</Button><Button variant="secondary" size="sm" onClick={() => change(() => moveCore(well, document, segment.id, 'below'), 'Сегменты переставлены.')}>Переставить ниже</Button></div>
        <details className="interpretation-editor-details"><summary>Разделить / объединить сегмент</summary><Field label="Разделить керн на глубине, м"><input type="number" step="0.1" value={splitAt} onChange={e => setSplitAt(Number(e.target.value))} /></Field><Button variant="secondary" size="sm" onClick={() => change(() => splitCore(well, document, segment.id, splitAt), 'Сегмент разделён; части проб сохранили номера и анализы.')}>Разделить сегмент</Button><div className="interpretation-actions"><Button size="sm" variant="secondary" onClick={() => change(() => mergeCore(well, document, segment.id, 'above'), 'Сегменты объединены.')}>Объединить с верхним</Button><Button size="sm" variant="secondary" onClick={() => change(() => mergeCore(well, document, segment.id, 'below'), 'Сегменты объединены.')}>Объединить с нижним</Button></div><p className="interpretation-note">Один тип и рейс; для керна — прилегание по бурению, одинаковые ориентация и наличие промера.</p></details>
        <details className="interpretation-editor-details"><summary>Мощность и контакт</summary><Field label="Мощность сегмента, м"><input type="number" min={0} step="0.1" value={size} onChange={e => setSize(Number(e.target.value))} /></Field><Field label="Фиксировать"><select value={anchor} onChange={e => setAnchor(e.target.value as typeof anchor)}><option value="top">Кровлю · сдвинуть нижние</option><option value="bottom">Подошву · сдвинуть верхние</option></select></Field><Button size="sm" variant="secondary" onClick={() => change(() => resizeCore(well, document, segment.id, size, anchor), 'Мощность изменена с каскадным переносом связанных данных.')}>Изменить мощность</Button><p className="interpretation-note">{measured ? 'Есть промер: допустима исходная мощность, 0,1 м или 0 по правилу РП.' : 'Без промера допустимо изменение мощности; соседние сегменты сдвигаются.'}</p><Field label="Контакт с нижним сегментом, м"><input type="number" step="0.1" value={contact} onChange={e => setContact(Number(e.target.value))} /></Field><Button size="sm" variant="secondary" onClick={() => change(() => moveCoreContact(well, document, segment.id, contact), 'Изменён контакт двух соседних сегментов.')}>Изменить контакт сегментов</Button></details>
        <details className="interpretation-editor-details"><summary>Вставить бескерновый интервал</summary><Field label="Мощность вставки, м"><input type="number" min="0.1" step="0.1" value={insertSize} onChange={e => setInsertSize(Number(e.target.value))} /></Field><Button size="sm" variant="secondary" onClick={() => change(() => insertNoCore(well, document, segment.id, insertSize), 'Вставлен бескерновый сегмент; нижние данные сдвинуты.')}>Вставить после сегмента</Button></details>
        <details className="interpretation-editor-details"><summary>Свойства сегмента</summary><form onSubmit={e => { e.preventDefault(); change(() => syncCore(well, { ...document, core: document.core.map(s => s.id === segment.id ? { ...s, properties } : s) }), 'Сводные свойства сегмента изменены.') }}><Field label="Порода сегмента"><select value={properties.rock} onChange={e => updateProperties({ rock: e.target.value as typeof properties.rock })}>{Object.entries(copy.rocks).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Минерализации сегмента"><input value={properties.mineralization} onChange={e => updateProperties({ mineralization: e.target.value, minerals: e.target.value.split(/[,;]/).map(v => v.trim()).filter(Boolean) })} /></Field>{!noCore && <Field label="Цвет сегмента"><select value={properties.color ?? 'gray'} onChange={e => updateProperties({ color: e.target.value as typeof properties.color })}>{Object.entries(copy.colors).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field>}<Field label="Описание сегмента"><textarea value={properties.note} onChange={e => updateProperties({ note: e.target.value })} /></Field><div className="interpretation-actions"><Button size="sm" type="submit">Применить свойства сегмента</Button><Button size="sm" variant="secondary" onClick={() => change(() => syncCore(well, { ...document, core: document.core.map(s => s.id === segment.id ? { ...s, properties: undefined } : s) }), 'Свойства восстановлены из исходной колонки.')}>Вернуть исходные свойства</Button></div></form></details>
        <Button size="sm" variant="quiet" className="interpretation-delete" onClick={() => { if (window.confirm('Удалить сегмент и сдвинуть нижние? Исходный сегмент сохранится для восстановления; вставленный бескерновый будет удалён полностью.')) change(() => deleteCore(well, document, segment.id), 'Сегмент удалён; исходные данные сохранены.') }}>Удалить сегмент</Button>
      </>}
      <details className="interpretation-editor-details"><summary>Операции рейса</summary><p className="interpretation-note">Сводный рейс: {run.from.toFixed(1)}–{run.to.toFixed(1)} м · выход {run.percent.toFixed(1)}%. Все его сегменты и связи изменятся вместе.</p><div className="interpretation-actions"><Button variant="secondary" size="sm" onClick={() => change(() => flipRun(well, document, segment.runId), 'Рейс перевёрнут со всеми связанными данными.')}>Перевернуть рейс</Button><Button variant="secondary" size="sm" onClick={() => change(() => moveRun(well, document, segment.runId, 'above'), 'Рейсы переставлены.')}>Рейс выше</Button><Button variant="secondary" size="sm" onClick={() => change(() => moveRun(well, document, segment.runId, 'below'), 'Рейсы переставлены.')}>Рейс ниже</Button></div></details>
    </fieldset>
    <div className="interpretation-linked"><strong>Связанные данные</strong><span>{sampleCount} отображаемых частей проб</span><span>{measured ? 'Промер присутствует' : 'Промера в этой части нет'}</span><span>Номера и лабораторные значения сохраняются</span></div>
    <p className="interpretation-note">Операции перестроят сводную литологию области керна, включая ручные правки. Undo вернёт весь результат вместе.</p>
  </div>
}

export type SampleDraft = { id: string; name: string; kind: SampleKind; from: number; to: number }
export function SampleEditor({ draft, well, document, segmentId, disabled, onApply, onDelete, onDirty }:
  { draft: SampleDraft; well: InterpretationWell; document: InterpretationDocument; segmentId?: string; disabled: boolean; onApply: (value: SampleDraft) => void; onDelete?: () => void; onDirty: () => void }) {
  const [value, setValue] = useState(draft)
  const patch = (next: Partial<SampleDraft>) => { setValue(v => ({ ...v, ...next })); onDirty() }
  const source = (document.samples ?? well.samples).find(s => s.id === draft.id)
  const neighbours = mappedSamples(well, document).filter(s => s.kind === value.kind && s.segmentId === segmentId && s.sampleId !== value.id)
  const upper = neighbours.filter(s => s.to <= value.from).sort((a, b) => b.to - a.to)[0], lower = neighbours.filter(s => s.from >= value.to).sort((a, b) => a.from - b.from)[0]
  return <form onSubmit={e => { e.preventDefault(); onApply(value) }}><div className="interpretation-inspector__summary"><span>{source ? 'Часть сводной пробы' : 'Новая сводная проба'}</span><strong>{copy.sampleKinds[value.kind]}</strong><small>Глубины по бурению рассчитаются автоматически</small></div><fieldset disabled={disabled}><Field label="Вид пробы"><select value={value.kind} onChange={e => patch({ kind: e.target.value as SampleKind })}>{Object.entries(copy.sampleKinds).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><Field label="Номер пробы"><input required value={value.name} onChange={e => patch({ name: e.target.value })} /></Field><div className="interpretation-fields-pair"><Field label="Проба от, м"><input required type="number" step="0.1" value={value.from} onChange={e => patch({ from: Number(e.target.value) })} /></Field><Field label="Проба до, м"><input required type="number" step="0.1" value={value.to} onChange={e => patch({ to: Number(e.target.value) })} /></Field></div><Field label="Мощность пробы, м"><input required type="number" min="0.1" step="0.1" value={Number((value.to - value.from).toFixed(3))} onChange={e => patch({ to: value.from + Number(e.target.value) })} /></Field><p className="interpretation-note">Лабораторный demo-показатель: {(source?.assay ?? 0).toFixed(3)}%. Изменение глубин не меняет анализ.</p><div className="interpretation-actions"><Button size="sm" type="submit">Применить пробу</Button><Button size="sm" variant="secondary" disabled={!upper} onClick={() => upper && patch({ from: upper.from })}>До верхней пробы</Button><Button size="sm" variant="secondary" disabled={!lower} onClick={() => lower && patch({ to: lower.to })}>До нижней пробы</Button></div>{onDelete && <Button size="sm" variant="quiet" className="interpretation-delete" onClick={onDelete}>Удалить эту часть пробы</Button>}</fieldset><p className="interpretation-note">Проба остаётся внутри одного кернового сегмента. Перекрытые пробы того же вида будут обрезаны; остальные виды сохранятся.</p></form>
}

export function RangeDeleteEditor({ from, to, rows, disabled, onApply, onCancel, onDirty }:
  { from: number; to: number; rows: { from: number; to: number }[]; disabled: boolean; onApply: (from: number, to: number) => void; onCancel: () => void; onDirty: () => void }) {
  const [start, setStart] = useState(from), [end, setEnd] = useState(to)
  const count = rows.filter(r => r.from >= start && r.to <= end).length
  return <form onSubmit={e => { e.preventDefault(); onApply(start, end) }}><div className="interpretation-inspector__summary"><span>Удаление группы</span><strong>{count} полностью попавших интервалов</strong><small>Частично попавшие интервалы сохранятся</small></div><fieldset disabled={disabled}><Field label="Удалить от, м"><input required type="number" step="0.1" value={start} onChange={e => { setStart(Number(e.target.value)); onDirty() }} /></Field><Field label="Удалить до, м"><input required type="number" step="0.1" value={end} onChange={e => { setEnd(Number(e.target.value)); onDirty() }} /></Field><div className="interpretation-actions"><Button variant="danger" size="sm" type="submit" disabled={!count}>Удалить группу</Button><Button variant="secondary" size="sm" onClick={onCancel}>Отменить удаление группы</Button></div></fieldset></form>
}
